import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'NeoEstate',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'onboard_title_1': 'NeoEstate Noir',
      'onboard_body_1': 'Luxurious noir nights meet bright skyline dreams.',
      'onboard_title_2': 'Ivory Sunrise',
      'onboard_body_2': 'Ivory warmth with yellow glow invites joy.',
      'onboard_title_3': 'Fusion Living',
      'onboard_body_3': 'Spin 3D galleries, compare instantly, book with a tap.',
      'login': 'Log in',
      'signup': 'Create account',
      'guest': 'Continue as guest',
      'email': 'Email',
      'phone': 'Phone',
      'password': 'Password',
      'confirm_password': 'Confirm password',
      'show_password': 'Show',
      'hide_password': 'Hide',
      'password_strength': 'Password strength',
      'forgot_password': 'Forgot password?',
      'find_place': 'Find Your Way Home',
      'search_hint': 'Search cities, areas, features…',
      'all': 'All',
      'recent_searches': 'Recent searches',
      'best_offer': 'Best Offer',
      'for_sale': 'For Sale',
      'for_rent': 'For Rent',
      'mortgage': 'Mortgage',
      'mortgage_badge': 'Mortgage ready',
      'details': 'Details',
      'description': 'Description',
      'facilities': 'Facilities',
      'beds': 'Beds',
      'beds_short': 'bd',
      'baths': 'Baths',
      'baths_short': 'ba',
      'area': 'Area',
      'city': 'City',
      'parking': 'Parking',
      'garden': 'Garden',
      'book_now': 'Book Now',
      'book_summary': 'Book Summary',
      'pick_date': 'Pick-up Date',
      'return_date': 'Return Date',
      'confirm_booking': 'Confirm booking',
      'booking_range_label': 'Pick-up: %s → Return: %s',
      'booking_slot_label': 'Time slot: %s',
      'booking_saved': 'Visit scheduled',
      'select_pick_date': 'Select your pick-up date',
      'select_return_date': 'Select your return date',
      'reset_selection': 'Reset selection',
      'price': 'Price',
      'monthly_payment': 'Monthly payment',
      'down_payment': 'Down payment %',
      'years': 'Years',
      'rate': 'Interest rate %',
      'catalog': 'Catalog',
      'filters': 'Filters',
      'filters_active': 'Filters active: %d',
      'sort': 'Sort',
      'sort_recommended': 'Recommended',
      'sort_price_low': 'Price: Low to High',
      'sort_price_high': 'Price: High to Low',
      'sort_area': 'Area: Largest first',
      'grid_view': 'Grid view',
      'list_view': 'List view',
      'apply': 'Apply',
      'clear': 'Clear',
      'compare': 'Compare',
      'add_to_compare': 'Add to compare',
      'favorites': 'Favorites',
      'notifications': 'Notifications',
      'mark_all_read': 'Mark all read',
      'marked_all_read': 'All notifications marked as read.',
      'swipe_to_mark_read': 'Swipe to mark as read.',
      'badge_new': 'New',
      'my_items': 'My Items',
      'add_item': 'Add item',
      'for_sale_now': 'Sell now',
      'wanted_price': 'Wanted price',
      'keep_item': 'Keep item',
      'tips': 'Tips & condition',
      'wanted_offers': 'Wanted offers',
      'ai_explain': 'Explain with AI',
      'ai_placeholder': 'This is an AI preview. Connect backend later.',
      'settings': 'Settings',
      'theme': 'Theme',
      'dark_mode': 'Dark mode',
      'light_mode': 'Light mode',
      'accent_color': 'Accent color',
      'language': 'Language',
      'english': 'English',
      'arabic': 'Arabic',
      'units': 'Units & currency',
      'clear_data': 'Clear local data',
      'clear_data_title': 'Reset experience?',
      'clear_data_message': 'This removes saved preferences, onboarding progress, and cached selections.',
      'data_cleared': 'Preferences cleared. Restarting onboarding…',
      'edit_profile': 'Edit profile name',
      'profile_updated': 'Profile updated.',
      'no_results': 'No results',
      'no_results_filters': 'Adjust filters to explore more homes.',
      'pull_to_refresh': 'Pull to refresh',
      'loading': 'Loading…',
      'try_again': 'Try again',
      'tutorial_1': 'Search anywhere here',
      'tutorial_2': 'Drag to spin 3D preview',
      'tutorial_3': 'Tap to compare items',
      'tutorial_4': 'Book a visit instantly',
      'tutorial_1_hint': 'Use smart filters and quick suggestions.',
      'tutorial_2_hint': 'Drag horizontally to scrub 3D frames.',
      'tutorial_3_hint': 'Tap chips to compare and filter instantly.',
      'tutorial_4_hint': 'Book visits without leaving the app.',
      'remember_me': 'Remember me',
      'name': 'Name',
      'strength_weak': 'Weak',
      'strength_medium': 'Medium',
      'strength_strong': 'Strong',
      'book_visit': 'Book visit',
      'mortgage_calculator': 'Mortgage calculator',
      'suggestions': 'Suggestions',
      'coach_skip': 'Skip tour',
      'coach_next': 'Next',
      'coach_done': 'Done',
      'guest_welcome': 'Continue as guest',
      'logout': 'Sign out',
      'login_success': 'Welcome back to NeoEstate!',
      'guest_mode_active': 'Exploring as guest.',
      'logout_success': 'Signed out successfully.',
      'compare_now': 'Compare now',
      'compare_count': 'Compare (%d)',
      'compare_cta': 'Open compare',
      'compare_min_notice': 'Select at least two properties to compare.',
      'coach_compare_hint': 'Compare tray keeps your picks ready.',
      'gallery': 'Gallery',
      'offers': 'Offers',
      'wanted': 'Wanted',
      'welcome_back': 'Welcome back,',
      'greeting_guest': 'Guest',
      'section_modern': 'Modern Capsules',
      'section_city': 'Cityscape Collection',
      'search': 'Search',
      'book': 'Book',
      'cancel': 'Cancel',
      'close': 'Close',
      'calendar': 'Calendar',
      'time_slots': 'Time slots',
      'save': 'Save',
      'clear_filters': 'Clear filters',
      'results': 'Results',
      'catalog_results': '%d listings',
      'compare_list': 'Compare list',
      'payment_plan': 'Payment plan',
      'offers_received': 'Offers received',
      'offers_received_count': 'Offers received: %d',
      'pending_offers_count': 'Pending offers: %d',
      'offers_pending_section': 'Pending offers',
      'offers_pending_empty': 'No offers waiting yet.',
      'offers_history_section': 'Offer history',
      'offers_history_empty': 'No previous offer decisions.',
      'offer_accept': 'Accept',
      'offer_decline': 'Decline',
      'offer_counter': 'Counter',
      'offer_counter_title': 'Counter offer',
      'offer_counter_message': 'Set a new price you would accept.',
      'offer_counter_label': 'Counter amount',
      'offer_counter_hint': 'Optional note',
      'offer_counter_submit': 'Send counter',
      'offer_counter_value': 'Counter offer: %s',
      'offer_response_note': 'Your note: %s',
      'offer_updated': 'Updated %s',
      'offer_status_pending': 'Pending',
      'offer_status_accepted': 'Accepted',
      'offer_status_declined': 'Declined',
      'offer_status_countered': 'Countered',
      'offer_response_accept': 'Offer accepted.',
      'offer_response_decline': 'Offer declined.',
      'offer_response_counter': 'Counter offer sent.',
      'notification_marked': 'Notification marked as read.',
      'notifications_offer_pending': 'New offer from %s',
      'notifications_offer_status': 'Offer with %s marked %t',
      'notification_booking_set': 'Visit scheduled for %s',
      'status_label': 'Status',
      'status_listed': 'Listed',
      'status_waiting': 'Waiting for offers',
      'status_reviewing': 'Reviewing',
      'status_sold': 'Sold',
      'notifications_empty': 'No notifications yet',
      'about': 'About',
      'version': 'Version 1.0.0',
      'yes': 'Yes',
      'no': 'No',
      'rating': 'Rating',
      'title_field': 'Title',
      'brand_field': 'Brand',
      'year_field': 'Year',
      'image_url': 'Image URL',
      'tips_placeholder': 'Tips comma separated',
      'max_price': 'Max price',
      'min_beds': 'Min beds',
      'min_baths': 'Min baths',
      'min_area': 'Min area (m²)',
      'city_filter': 'City',
      'apply_accent': 'Apply accent',
      'hue': 'Hue',
      'saturation': 'Saturation',
      'lightness': 'Lightness',
      'total_interest': 'Total interest',
      'monthly_label': 'Monthly',
      'interest_label': 'Interest',
      'offer_amount': 'Offer amount',
      'offer_from': 'From',
    },
    'ar': {
      'app_name': 'نيو إستيت',
      'skip': 'تخطي',
      'next': 'التالي',
      'get_started': 'ابدأ الآن',
      'onboard_title_1': 'نيو إستيت نوار',
      'onboard_body_1': 'ليالٍ فاخرة داكنة تلتقي بأحلام أفق براقة.',
      'onboard_title_2': 'شروق العاج',
      'onboard_body_2': 'دفء عاجي مع وهج أصفر يدعو للبهجة.',
      'onboard_title_3': 'معيشة مندمجة',
      'onboard_body_3': 'استعرض ثلاثي الأبعاد، قارِن فورًا، واحجز بضغطة.',
      'login': 'تسجيل الدخول',
      'signup': 'إنشاء حساب',
      'guest': 'الدخول كضيف',
      'email': 'البريد الإلكتروني',
      'phone': 'الهاتف',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'show_password': 'إظهار',
      'hide_password': 'إخفاء',
      'password_strength': 'قوة كلمة المرور',
      'forgot_password': 'نسيت كلمة المرور؟',
      'find_place': 'ابحث عن مكانك المثالي',
      'search_hint': 'ابحث عن مدن، مناطق، خصائص…',
      'all': 'الكل',
      'recent_searches': 'عمليات البحث الأخيرة',
      'best_offer': 'أفضل عرض',
      'for_sale': 'للبيع',
      'for_rent': 'للإيجار',
      'mortgage': 'تمويل عقاري',
      'mortgage_badge': 'جاهز للتمويل',
      'details': 'التفاصيل',
      'description': 'الوصف',
      'facilities': 'المرافق',
      'beds': 'غرف',
      'beds_short': 'غ',
      'baths': 'حمامات',
      'baths_short': 'حم',
      'area': 'المساحة',
      'city': 'المدينة',
      'parking': 'موقف',
      'garden': 'حديقة',
      'book_now': 'احجز الآن',
      'book_summary': 'ملخص الحجز',
      'pick_date': 'تاريخ الزيارة',
      'return_date': 'تاريخ العودة',
      'confirm_booking': 'تأكيد الحجز',
      'booking_range_label': 'الزيارة: %s → العودة: %s',
      'booking_slot_label': 'وقت الزيارة: %s',
      'booking_saved': 'تم جدولة الزيارة',
      'select_pick_date': 'اختر تاريخ الزيارة',
      'select_return_date': 'اختر تاريخ العودة',
      'reset_selection': 'إعادة التحديد',
      'price': 'السعر',
      'monthly_payment': 'القسط الشهري',
      'down_payment': 'الدفعة الأولى %',
      'years': 'سنوات',
      'rate': 'نسبة الفائدة %',
      'catalog': 'الكتالوج',
      'filters': 'فلاتر',
      'filters_active': 'الفلاتر المفعلة: %d',
      'sort': 'ترتيب',
      'sort_recommended': 'موصى به',
      'sort_price_low': 'السعر: من الأقل للأعلى',
      'sort_price_high': 'السعر: من الأعلى للأقل',
      'sort_area': 'المساحة: الأكبر أولاً',
      'grid_view': 'عرض شبكي',
      'list_view': 'عرض قائمة',
      'apply': 'تطبيق',
      'clear': 'مسح',
      'compare': 'مقارنة',
      'add_to_compare': 'إضافة للمقارنة',
      'favorites': 'المفضلة',
      'notifications': 'الإشعارات',
      'mark_all_read': 'وضع الكل كمقروء',
      'marked_all_read': 'تم تعليم جميع الإشعارات كمقروءة.',
      'swipe_to_mark_read': 'اسحب لوضع الإشعار كمقروء.',
      'badge_new': 'جديد',
      'my_items': 'مقتنياتي',
      'add_item': 'إضافة عنصر',
      'for_sale_now': 'بيع الآن',
      'wanted_price': 'السعر المرغوب',
      'keep_item': 'الاحتفاظ بالعنصر',
      'tips': 'نصائح والحالة',
      'wanted_offers': 'عروض مرغوبة',
      'ai_explain': 'تفسير بالذكاء الاصطناعي',
      'ai_placeholder': 'هذه معاينة ذكاء اصطناعي. سيتم الربط لاحقًا.',
      'settings': 'الإعدادات',
      'theme': 'السمة',
      'dark_mode': 'الوضع الداكن',
      'light_mode': 'الوضع الفاتح',
      'accent_color': 'اللون الرئيسي',
      'language': 'اللغة',
      'english': 'الإنجليزية',
      'arabic': 'العربية',
      'units': 'الوحدات والعملة',
      'clear_data': 'مسح البيانات المحلية',
      'clear_data_title': 'إعادة تعيين التجربة؟',
      'clear_data_message': 'سيتم حذف التفضيلات المحفوظة وتقدم الجولة والاختيارات المخزنة.',
      'data_cleared': 'تم مسح التفضيلات. سيتم إعادة تشغيل الإرشاد…',
      'edit_profile': 'تعديل اسم الملف الشخصي',
      'profile_updated': 'تم تحديث الملف الشخصي.',
      'no_results': 'لا توجد نتائج',
      'no_results_filters': 'قم بتعديل الفلاتر لاستكشاف المزيد من العقارات.',
      'pull_to_refresh': 'اسحب للتحديث',
      'loading': 'جار التحميل…',
      'try_again': 'أعد المحاولة',
      'tutorial_1': 'ابحث من هنا',
      'tutorial_2': 'اسحب لاستعراض ثلاثي الأبعاد',
      'tutorial_3': 'اضغط للمقارنة',
      'tutorial_4': 'احجز زيارة فورًا',
      'tutorial_1_hint': 'استخدم الفلاتر الذكية والاقتراحات السريعة.',
      'tutorial_2_hint': 'اسحب أفقيًا للتنقل بين الإطارات الثلاثية.',
      'tutorial_3_hint': 'اضغط على الشرائح للمقارنة والتصفية مباشرة.',
      'tutorial_4_hint': 'احجز زيارتك دون مغادرة التطبيق.',
      'remember_me': 'تذكرني',
      'name': 'الاسم',
      'strength_weak': 'ضعيف',
      'strength_medium': 'متوسط',
      'strength_strong': 'قوي',
      'book_visit': 'احجز زيارة',
      'mortgage_calculator': 'حاسبة التمويل العقاري',
      'suggestions': 'اقتراحات',
      'coach_skip': 'تخطي الجولة',
      'coach_next': 'التالي',
      'coach_done': 'تم',
      'guest_welcome': 'الدخول كضيف',
      'logout': 'تسجيل الخروج',
      'login_success': 'مرحبًا بعودتك إلى نيو إستيت!',
      'guest_mode_active': 'تتصفح كتجربة ضيف.',
      'logout_success': 'تم تسجيل الخروج بنجاح.',
      'compare_now': 'قارن الآن',
      'compare_count': 'مقارنة (%d)',
      'compare_cta': 'افتح صفحة المقارنة',
      'compare_min_notice': 'اختر عنصرين على الأقل للمقارنة.',
      'coach_compare_hint': 'شريط المقارنة يحتفظ باختياراتك جاهزة.',
      'gallery': 'معرض',
      'offers': 'عروض',
      'wanted': 'مرغوب',
      'welcome_back': 'مرحبًا بعودتك،',
      'greeting_guest': 'ضيف',
      'section_modern': 'مساحات عصرية',
      'section_city': 'مجموعة المدينة',
      'search': 'بحث',
      'book': 'احجز',
      'cancel': 'إلغاء',
      'close': 'إغلاق',
      'calendar': 'تقويم',
      'time_slots': 'أوقات متاحة',
      'save': 'حفظ',
      'clear_filters': 'مسح الفلاتر',
      'results': 'النتائج',
      'catalog_results': '%d عقار',
      'compare_list': 'قائمة المقارنة',
      'payment_plan': 'خطة الدفع',
      'offers_received': 'عروض مستلمة',
      'offers_received_count': 'عروض مستلمة: %d',
      'pending_offers_count': 'عروض قيد الانتظار: %d',
      'offers_pending_section': 'عروض قيد الانتظار',
      'offers_pending_empty': 'لا توجد عروض قيد الانتظار بعد.',
      'offers_history_section': 'سجل العروض',
      'offers_history_empty': 'لا توجد قرارات عروض سابقة.',
      'offer_accept': 'قبول',
      'offer_decline': 'رفض',
      'offer_counter': 'عرض مقابل',
      'offer_counter_title': 'عرض مقابل',
      'offer_counter_message': 'حدد سعراً جديداً ترغب بقبوله.',
      'offer_counter_label': 'المبلغ المقابل',
      'offer_counter_hint': 'ملاحظة اختيارية',
      'offer_counter_submit': 'إرسال العرض المقابل',
      'offer_counter_value': 'عرض مقابل: %s',
      'offer_response_note': 'ملاحظتك: %s',
      'offer_updated': 'تم التحديث %s',
      'offer_status_pending': 'قيد الانتظار',
      'offer_status_accepted': 'تم القبول',
      'offer_status_declined': 'تم الرفض',
      'offer_status_countered': 'عرض مقابل',
      'offer_response_accept': 'تم قبول العرض.',
      'offer_response_decline': 'تم رفض العرض.',
      'offer_response_counter': 'تم إرسال العرض المقابل.',
      'notification_marked': 'تم وضع الإشعار كمقروء.',
      'notifications_offer_pending': 'عرض جديد من %s',
      'notifications_offer_status': 'عرض مع %s تم وسمه %t',
      'notification_booking_set': 'تم جدولة الزيارة لـ %s',
      'status_label': 'الحالة',
      'status_listed': 'معروض',
      'status_waiting': 'بانتظار العروض',
      'status_reviewing': 'قيد المراجعة',
      'status_sold': 'تم البيع',
      'notifications_empty': 'لا توجد إشعارات بعد',
      'about': 'حول',
      'version': 'الإصدار 1.0.0',
      'yes': 'نعم',
      'no': 'لا',
      'rating': 'تقييم',
      'title_field': 'العنوان',
      'brand_field': 'العلامة',
      'year_field': 'السنة',
      'image_url': 'رابط الصورة',
      'tips_placeholder': 'نصائح مفصولة بفواصل',
      'max_price': 'أقصى سعر',
      'min_beds': 'أدنى غرف',
      'min_baths': 'أدنى حمامات',
      'min_area': 'أدنى مساحة (م²)',
      'city_filter': 'المدينة',
      'apply_accent': 'تطبيق اللون',
      'hue': 'التدرج',
      'saturation': 'الإشباع',
      'lightness': 'الإضاءة',
      'total_interest': 'إجمالي الفائدة',
      'monthly_label': 'شهري',
      'interest_label': 'فائدة',
      'offer_amount': 'قيمة العرض',
      'offer_from': 'من',
    },
  };

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static List<Locale> get supportedLocales => const [Locale('en'), Locale('ar')];

  String t(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']![key] ??
        key;
  }

  bool get isRTL => locale.languageCode == 'ar';
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture(AppLocalizations(locale));
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
